services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: pokemon
      POSTGRES_PASSWORD: pokemon1234
      POSTGRES_DB: pokemon
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
